version: '3.7'
services: 
  redis:
    image: redis/redis-stack-server:latest 
    container_name: redis-stack-server
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 7000:6379
    expose: 
      - 6379

  api:
    build: .
    container_name: api
    restart: unless-stopped
    network_mode: bridge
    command: /bin/sh -c 'nodemon -e js, html index.js'
    ports:
      - 8080:9000
    volumes: 
      - .:/src
      - /src/node_modules
    links:
      - redis
          
        #database: 
        #  image: postgres:latest
        #  environment:
        #          POSTGRES_USER: 'postgres'
        #          POSTGRES_PASSWORD: 'root'
        #          POSTGRES_DB: 'postgres'
        #  network_mode: bridge
        #  ports:
        #    - 35432:5432
        #  volumes:
        #      - /var/lib/postgresql/14/main
